// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/cores/ports/ports.go
//
// Generated by this command:
//
//	mockgen -source=./internal/cores/ports/ports.go -destination=test/mock/./cores/ports/ports.go
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	chromedp "github.com/chromedp/chromedp"
	entities "github.com/savioruz/simeru-scraper/internal/cores/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockScrapeRepository is a mock of ScrapeRepository interface.
type MockScrapeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScrapeRepositoryMockRecorder
	isgomock struct{}
}

// MockScrapeRepositoryMockRecorder is the mock recorder for MockScrapeRepository.
type MockScrapeRepositoryMockRecorder struct {
	mock *MockScrapeRepository
}

// NewMockScrapeRepository creates a new mock instance.
func NewMockScrapeRepository(ctrl *gomock.Controller) *MockScrapeRepository {
	mock := &MockScrapeRepository{ctrl: ctrl}
	mock.recorder = &MockScrapeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapeRepository) EXPECT() *MockScrapeRepositoryMockRecorder {
	return m.recorder
}

// ScrapeSchedule mocks base method.
func (m *MockScrapeRepository) ScrapeSchedule(ctx context.Context, opts ...chromedp.ExecAllocatorOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScrapeSchedule", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScrapeSchedule indicates an expected call of ScrapeSchedule.
func (mr *MockScrapeRepositoryMockRecorder) ScrapeSchedule(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrapeSchedule", reflect.TypeOf((*MockScrapeRepository)(nil).ScrapeSchedule), varargs...)
}

// ScrapeStudyPrograms mocks base method.
func (m *MockScrapeRepository) ScrapeStudyPrograms(ctx context.Context, opts ...chromedp.ExecAllocatorOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScrapeStudyPrograms", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScrapeStudyPrograms indicates an expected call of ScrapeStudyPrograms.
func (mr *MockScrapeRepositoryMockRecorder) ScrapeStudyPrograms(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrapeStudyPrograms", reflect.TypeOf((*MockScrapeRepository)(nil).ScrapeStudyPrograms), varargs...)
}

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// GetSchedule mocks base method.
func (m *MockScheduleRepository) GetSchedule(studyPrograms, day string) (*[]entities.RowData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedule", studyPrograms, day)
	ret0, _ := ret[0].(*[]entities.RowData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedule indicates an expected call of GetSchedule.
func (mr *MockScheduleRepositoryMockRecorder) GetSchedule(studyPrograms, day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedule", reflect.TypeOf((*MockScheduleRepository)(nil).GetSchedule), studyPrograms, day)
}

// GetStudyPrograms mocks base method.
func (m *MockScheduleRepository) GetStudyPrograms(faculty string) (*[]entities.StudyPrograms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyPrograms", faculty)
	ret0, _ := ret[0].(*[]entities.StudyPrograms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyPrograms indicates an expected call of GetStudyPrograms.
func (mr *MockScheduleRepositoryMockRecorder) GetStudyPrograms(faculty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyPrograms", reflect.TypeOf((*MockScheduleRepository)(nil).GetStudyPrograms), faculty)
}
